// Generated by CoffeeScript 1.9.0
(function() {

  var gulp = require('gulp');

  gulp.task('copy', function() {
    gulp.src(['source/images/*.png', 'source/images/**/*.png', '!source/images/sprite/*', '!source/images/sprite/'])
      .pipe(gulp.dest('build/img'));
    gulp.src('source/fonts/*.woff')
      .pipe(gulp.dest('build/fonts'));
  });

}).call(this);
