// Generated by CoffeeScript 1.9.0
(function() {
  var gulp, imagemin;

  gulp = require('gulp');

  imagemin = require('gulp-imagemin');

  gulp.task('imagemin', function() {
    return gulp.src(['source/images/*.jpg', 'source/images/**/*.jpg']).pipe(imagemin({
      progressive: true
    })).pipe(gulp.dest('build/img'));
  });

}).call(this);
