// Generated by CoffeeScript 1.9.0
(function() {
  var connect, gulp, jade, plumber, changed;

  gulp = require('gulp');

  jade = require('gulp-jade');

  connect = require('gulp-connect');

  plumber = require('gulp-plumber');

  changed = require('gulp-changed');

  gulp.task('jade', function() {
    return gulp.src('source/jade/*.jade')
      .pipe(plumber())
      .pipe(changed('build', {extension: '.html'}))
      .pipe(
        jade({
          pretty: true
        })
      )
      .pipe(gulp.dest('build'))
      .pipe(connect.reload());
  });

}).call(this);
