// Generated by CoffeeScript 1.9.0
(function() {
  var gulp, spritesmith;

  gulp = require('gulp');

  spritesmith = require('gulp.spritesmith');

  gulp.task('sprite', function() {
    var spriteData;
    spriteData = gulp.src('source/images/sprite/*.png').pipe(spritesmith({
      imgName: 'sprite.png',
      cssName: 'sprite.styl',
      cssFormat: 'stylus',
      padding: 5,
      algorithm: 'binary-tree',
      cssTemplate: 'source/stylus/inc/stylus.template.mustache',
      cssVarMap: function(sprite) {
        sprite.name = "s-" + sprite.name;
      }
    }));
    spriteData.img.pipe(gulp.dest('build/img'));
    return spriteData.css.pipe(gulp.dest('source/stylus/inc'));
  });

}).call(this);
