// Generated by CoffeeScript 1.9.0
(function() {
  var autoprefixer, mmq, connect, csso, gulp, plumber, stylus, rename;

  gulp = require('gulp');

  rename = require('gulp-rename');

  stylus = require('gulp-stylus');

  mmq = require('gulp-merge-media-queries');

  csso = require('gulp-csso');

  autoprefixer = require('gulp-autoprefixer');

  connect = require('gulp-connect');

  plumber = require('gulp-plumber');

  gulp.task('stylus', function() {
    return gulp.src('source/stylus/common.styl').pipe(stylus()).pipe(mmq({
      log: true
    })).pipe(autoprefixer({
      browsers: '> 1%',
      cascade: false
    }))
    .pipe(csso())
    .pipe(rename({
      suffix: '.min'
    }))
    .pipe(gulp.dest('build/css'))
    .pipe(connect.reload());
  });

}).call(this);
