// Generated by CoffeeScript 1.9.0
(function() {
  var gulp, ttf2woff;

  gulp = require('gulp');

  ttf2woff = require('gulp-ttf2woff');

  gulp.task('ttf2woff', function() {
    return gulp.src(['source/fonts/*.ttf']).pipe(ttf2woff()).pipe(gulp.dest('build/fonts'));
  });

}).call(this);
