// Generated by CoffeeScript 1.9.0
(function() {
  var gulp;

  gulp = require('gulp');

  gulp.task('watch', function() {
    gulp.watch(['source/jade/*', 'source/jade/**/*.jade'], ['jade']);
    gulp.watch(['source/stylus/*', 'source/stylus/**/*', 'source/pages/**/*.styl'], ['stylus']);
    gulp.watch(['source/images/*.png', 'source/images/**/*.png', 'source/scripts/*.js', 'source/fonts/*.woff', '!source/images/sprite/', '!source/images/sprite/*'], ['copy']);
    gulp.watch(['source/images/*.jpg', 'source/images/**/*.jpg', '!source/images/sprite/', '!source/images/sprite/*'], ['imagemin']);
    gulp.watch(['source/images/sprite/*.png'], ['sprite']);
    gulp.watch(
      [
        'source/scripts/vendor-scripts/*.js',
        'source/scripts/client.js'
      ]
      , ['javascript']);
    gulp.watch(['source/stylus/vendor-css/*.css'], ['css']);
    gulp.watch(['source/fonts/*.ttf'], ['ttf2woff']);
  });

}).call(this);
